### ISSUE TITLE
Plugin is not compatible with 0.6.X   

### ISSUE THREAD

**Issue by Kuznetsof** [kosyak/nodebb-plugin-coub#2]
Are you planning to make this work any time soon?

**Comment by kosyak** [comment]
Not within the following 2 weeks, sorry



—

**Comment by kosyak** [comment]
Fixed in 0.0.10

**Comment by Kuznetsof** [comment]
Awesome, let me test this one.

**Comment by Kuznetsof** [comment]
Yep, thanks brother works just fine! 
Do you know how i can change the default coub size, looks like they a bit smaller than on original site?

**Comment by kosyak** [comment]
The most straightforward way for now, I guess, is to install the plugin, change this line https://github.com/kosyak/nodebb-plugin-coub/blob/master/library.js#L5 in `node_modules/nodebb-plugin-coub/library.js` to something like 
```html
embed = '<div class="js-coub" data-width="800" data-height="600" data-coub-id="$1"></div>';
```
and restart nodebb. I'll try to add these values as config parameters to the admin panel.

**Comment by Kuznetsof** [comment]
That works. Thanks again!
